In [1]:
# Importing torch library
import torch

In [2]:
# Creating tensor using torch.tensot fucntion
x = torch.tensor([5, 3])
y = torch.tensor([2, 4])

In [3]:
# Multiplying tensors
x*y

tensor([10, 12])

In [4]:
# Creating torch Values
x = torch.zeros([2, 5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [5]:
#Getting the Size of the tensor
x.shape

torch.Size([2, 5])

In [6]:
#generating random value
y = torch.rand([2, 5])

In [7]:
y

tensor([[0.7576, 0.1545, 0.1421, 0.4160, 0.5296],
        [0.6514, 0.0965, 0.5451, 0.2965, 0.0331]])

In [8]:
y.view([1, 10])

tensor([[0.7576, 0.1545, 0.1421, 0.4160, 0.5296, 0.6514, 0.0965, 0.5451, 0.2965,
         0.0331]])

In [9]:
y

tensor([[0.7576, 0.1545, 0.1421, 0.4160, 0.5296],
        [0.6514, 0.0965, 0.5451, 0.2965, 0.0331]])

In [10]:
# .view doesn't change the value of the y varialble so you have to re assign the value.
y = y.view([1, 10])

In [11]:
y

tensor([[0.7576, 0.1545, 0.1421, 0.4160, 0.5296, 0.6514, 0.0965, 0.5451, 0.2965,
         0.0331]])